afsy/website

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_03.html.twig
Added non-breakable spaces after `:` signs, fixed all reviews by @xavierlacot 👍
=> Fixes for day 3 article

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_03.html.twig
=> Fix typo in day 3 article

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_14.html.twig
=> Fix markup and style on 14th post

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_01.html.twig
=> Add missing numbering for the fifth tip

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_19.html.twig
Corrections de quelques coquilles
=> Fix some issues Article 2017_19

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_21.html.twig
As the project doesn't work on Heroku (because of no background tasks and no websockets for PHP projects), I had to remove all mentions and links to it...
=> [Avent/2017-21] Remove links/mentions to Heroku

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_20.html.twig
=> Fix typos in the ElasticSearch article

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_17.html.twig
=> Fix mistakes in the React article

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_23.html.twig
=> Fix mistakes in the architecture article

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_14.html.twig
=> Remove duplicate text

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_16.html.twig
=> Fix typo in the security tips article

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_21.html.twig
=> Fix the websocket article

src/Afsy/Bundle/FrontBundle/Resources/views/Avent/day_2017_03.html.twig
Else, only homepage would work
=> Add nginx config to Flex & Heroku presentation

.symfony.cloud.yaml, .symfony/routes.yaml, .symfony/services.yaml, php.ini
=> feat(hosting): add symfonycloud configuration

.symfony.cloud.yaml, composer.json, composer.lock, config/packages/hwi_oauth.yaml, symfony.lock
This commit fixes dependencies and upgrade them (for CVE).
=> Prepare project to SfCloud

templates/Avent/2019/day_01.html.twig
=> Corrections de typos pour le premier article

.github/workflows/php.yml, .gitignore, behat.yml.dist, composer.json, composer.lock, config/packages/test/security.yaml, features/avent.feature, features/bootstrap/AbstractContext.php, features/bootstrap/FeatureContext.php, features/bootstrap/bootstrap.php, symfony.lock
Pour tester que tout va bien sur le calendrier de l'avent !
=> Ajout de tests fonctionnels

README.md, symfony.lock
After upgrade we didn't update the entire readme.
=> Update README with real commands

templates/Avent/2019/day_02.html.twig
The day 2 article was missing a title :)
=> Add a title on the Day 2 article

README.md, assets/css/avent.css, src/Controller/AventController.php, symfony.lock, templates/Blog/index.html.twig, templates/header.html.twig
Add a message on the homepage:
=> Add an announcement on the homepage about the calendar

src/Controller/AventController.php, templates/Avent/2019/day_05.html.twig
Preview: https://afsy.fr.pr-190-pcovu3i-esyx3y2kpl5ku.eu.s5y.io/avent/2019/05-structurez-votre-monolithe
=> article 5 : structurez votre monolithe

src/Controller/AventController.php, templates/Avent/2019/day_08.html.twig
je ferai le rebase après la publication de l'article du 6 voire du 7
Preview dispo ici: http://afsy.fr.pr-196-kui3bsi-esyx3y2kpl5ku.eu.s5y.io/avent/2019
=> Avent 2019-12-08 rex sf2 to sf4 back

templates/Avent/year.atom.twig
=> Fix article dates in the Atom feed

templates/Avent/2019/day_07.html.twig
Closes #202
This is similar to the PR #203 but for another article still suffering from that issue.
=> Fix HTML escaping in the article for day 7

templates/Avent/2019/day_15.html.twig
Une petite PR pour apporter quelques précisions sur mon article du 15 suite à des retours tardifs ;)
Merci @Nek- :100: pour le suivi du calendrier de l'Avent et le merge des PR.
=> Adjust some little things for day 15

src/Controller/AventController.php, templates/Avent/2017/day_07.html.twig, templates/Avent/2019/day_14.html.twig
:tada:
J'espère que ça fait pas trop fouillis et que j'enfonce pas trop de portes ouvertes :joy: 
Preview: http://afsy.fr.pr-213-5xihixq-esyx3y2kpl5ku.eu.s5y.io/avent/2019
=> Article du 14 décembre

src/Controller/AventController.php, templates/Avent/2019/day_19.html.twig
🎲 
Preview dispo ici : http://afsy.fr.pr-197-sg4m6za-esyx3y2kpl5ku.eu.s5y.io/avent/2019
=> Calendrier de l'avent : jour 19

templates/Avent/2019/day_19.html.twig
=> Fix the implementation of the DiceRoller

templates/Avent/2019/day_24.html.twig
Coucou,
je n'ai pas encore terminé l'article (j'aimerais ajouter une 3e partie), mais vous pouvez déjà commencer la relecture :)
Merci,
Nicolas
Preview: https://afsy.fr.pr-223-frl2lwi-esyx3y2kpl5ku.eu.s5y.io/
=> Add day 24

templates/Blog/index.html.twig
As december was last year already, we can disable this announcement :sunglasses:
=> Remove the Advent Calendar announcement

templates/Avent/2019/day_24.html.twig
Synchro avec l'article en anglais.
=> Improve day24 article

.gitignore, docker-compose.override.yml.dist, docker-compose.yml
=> Allow local override docker-compose
